Develop
MarkFialko/mesto pull request #4
Opened 2022-05-18 17:57 UTC by MarkFialko

2022-05-19 08:56 UTC, Kuzuru commented
Попап добавления нового места позволяет добавлять пустой пробел
![image](https://user-images.githubusercontent.com/49472529/169254738-b4866a31-121b-4a66-87bc-6b090f318f2f.png)

2022-05-19 08:59 UTC, Kuzuru commented
Пропадают лайки при добавлении новой карточки

2022-05-19 09:02 UTC, Kuzuru requested changes

2022-05-19 09:02 UTC, Kuzuru commented on blocks/popup/__close/popup__close.js
> +    form ? (form.closest(".popup__card") ? form.reset() : null) : null;
На этой строке я упал со стула

2022-05-19 13:40 UTC, MarkFialko commented on blocks/popup/__close/popup__close.js
> +    form ? (form.closest(".popup__card") ? form.reset() : null) : null;
ахахахаххааххахаха

2022-05-21 10:59 UTC, Kuzuru requested changes

2022-05-21 10:59 UTC, Kuzuru commented on blocks/pages/index.js
> +import { hideInputError} from "./../input-error/input-error.js"
У вас лишний пробел, мужчина. Не забывайте форматировать проект

2022-05-21 10:59 UTC, Kuzuru commented on blocks/pages/index.js
> +import {addPenButton,addCardButton} from "./../popup/__button/popup__buton.js"
А здесь пробел пропал...

2022-05-21 10:59 UTC, Kuzuru commented on blocks/popup/__button/popup__buton.js
> +    changeButton(button,settings,true);
Разделяй вызовы методов, создания переменных, а также прочей логики, которая друг с другом **не** связана

2022-05-21 10:59 UTC, Kuzuru commented on blocks/popup/__form/popup__form.js
> +    if (e.target.closest(".popup__user")) {
Почему ты используешь closest?

2022-05-21 10:59 UTC, Kuzuru commented on blocks/popup/popup.js
> +export function checkEscape(e,popupSelector,button,settings) {
Разделяй пустыми строками логику импортов и экспортов

2022-05-21 10:59 UTC, Kuzuru commented on blocks/validity/validity.js
> +        formElement.addEventListener("submit", function (evt) {
Вопрос к `... function (evt) { ...`: почему в некоторых файлах ты называешь переменную для `event` как `e`, а в других `evt`? Выдерживай одну логику именования переменных для повторяющихся структур

2022-05-21 10:59 UTC, Kuzuru commented on blocks/validity/validity__form/validity__form.js
> +    return countValidity === inputs.length ? true : false;
Что????

А, типо, просто `countValidity === inputs.length` уже не канает, да?

2022-05-21 10:59 UTC, Kuzuru commented on blocks/validity/validity__input/validity__input.js
> +    }
Этот `else` уже явно не нужен, так как он выполнится в любом случае, если предыдущие два ветвления не выполнились

2022-05-22 07:18 UTC, Kuzuru approved these changes

2022-05-22 11:25 UTC, merged